default: &default
  adapter: postgresql
  encoding: UTF-8
  host: localhost
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blogger1_development
  username: test
  password: test
  
test:
  <<: *default
  database: blogger1_test
  username: test
  password: test

production:
  <<: *default
  database: blogger1_production
  username: <%= ENV.fetch("BASE_PROJECT_DATABASE_USERNAME") { nil } %>
  password: <%= ENV.fetch("BASE_PROJECT_DATABASE_PASSWORD") { nil } %>